import "./globals.css";
import { CartProvider } from "./context/CartContext";
import ClientOnlyToast from "./components/ClientOnlyToast"; // Import the client-only toast

export const metadata = {
  title: "Store App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased bg-white dark:bg-black text-black dark:text-white`}
      >
        <CartProvider>
          {children}
          <ClientOnlyToast />
        </CartProvider>
      </body>
    </html>
  );
}
