import localFont from "next/font/local";
import "./globals.css";
import { CartProvider } from "./context/CartContext";
import ClientOnlyToast from "./components/ClientOnlyToast"; // Import the client-only toast

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Store App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          {children}
          <ClientOnlyToast />
        </CartProvider>
      </body>
    </html>
  );
}
